name: rasa
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - black
  - jupyter
  - python-dotenv
  - pip:
      - rasa
      - email-validator
      - phonenumbers
      # - flask

